import 'package:audioplayers/audioplayers.dart';
import 'dart:math';

class TaskSound {
  static AudioPlayer? _player;
  late String source;

  //choosing a random sound from the list in assets/Audio/SpecialTaskSounds/valorant_kill_sounds
  void sourceInitialization() {
    List<String> sounds = [
      "Aemondir Kill 1.mp3",
      "Aemondir Kill 2.mp3",
      "Aemondir Kill 3.mp3",
      "Aemondir Kill 4.mp3",
      "Araxys Kill 1.mp3",
      "Araxys Kill 2.mp3",
      "Araxys Kill 3.mp3",
      "Araxys Kill 4.mp3",
      "Base Kill 1.mp3",
      "Base Kill 2.mp3",
      "Base Kill 3.mp3",
      "Base Kill 4.mp3",
      "BlastX Kill 1.mp3",
      "BlastX Kill 2.mp3",
      "BlastX Kill 3.mp3",
      "BlastX Kill 4.mp3",
      "Champions 2021 Kill 1.mp3",
      "Champions 2021 Kill 2.mp3",
      "Champions 2021 Kill 3.mp3",
      "Champions 2021 Kill 4.mp3",
      "Champions 2022 Kill 1.mp3",
      "Champions 2022 Kill 2.mp3",
      "Champions 2022 Kill 3.mp3",
      "Champions 2022 Kill 4.mp3",
      "Champions 2024 Kill 1.mp3",
      "Champions 2024 Kill 2.mp3",
      "Champions 2024 Kill 3.mp3",
      "Champions 2024 Kill 4.mp3",
      "Champions_2023_Kill_1.mp3",
      "Champions_2023_Kill_2.mp3",
      "Champions_2023_Kill_3.mp3",
      "Champions_2023_Kill_4.mp3",
      "ChronoVoid Kill 1.mp3",
      "ChronoVoid Kill 2.mp3",
      "ChronoVoid Kill 3.mp3",
      "ChronoVoid Kill 4.mp3",
      "Cryostasis Kill 1.mp3",
      "Cryostasis Kill 2.mp3",
      "Cryostasis Kill 3.mp3",
      "Cryostasis Kill 4.mp3",
      "Elderflame Kill 1.mp3",
      "Elderflame Kill 2.mp3",
      "Elderflame Kill 3.mp3",
      "Elderflame Kill 4.mp3",
      "Evori Dreamwings Kill 1.mp3",
      "Evori Dreamwings Kill 2.mp3",
      "Evori Dreamwings Kill 3.mp3",
      "Evori Dreamwings Kill 4.mp3",
      "Forsaken Kill 1.mp3",
      "Forsaken Kill 2.mp3",
      "Forsaken Kill 3.mp3",
      "Forsaken Kill 4.mp3",
      "Gaia_s Vengeance Kill 1.mp3",
      "Gaia_s Vengeance Kill 2.mp3",
      "Gaia_s Vengeance Kill 3.mp3",
      "Gaia_s Vengeance Kill 4.mp3",
      "Glitchpop Kill 1.mp3",
      "Glitchpop Kill 2.mp3",
      "Glitchpop Kill 3.mp3",
      "Glitchpop Kill 4.mp3",
      "Imperium Kill 1.mp3",
      "Imperium Kill 2.mp3",
      "Imperium Kill 3.mp3",
      "Imperium Kill 4.mp3",
      "Ion Kill 1.mp3",
      "Ion Kill 2.mp3",
      "Ion Kill 3.mp3",
      "Ion Kill 4.mp3",
      "Kuronami Kill 1.mp3",
      "Kuronami Kill 2.mp3",
      "Kuronami Kill 3.mp3",
      "Kuronami Kill 4.mp3",
      "Magepunk Kill 1.mp3",
      "Magepunk Kill 2.mp3",
      "Magepunk Kill 3.mp3",
      "Magepunk Kill 4.mp3",
      "Mystbloom Kill 1.mp3",
      "Mystbloom Kill 2.mp3",
      "Mystbloom Kill 3.mp3",
      "Mystbloom Kill 4.mp3",
      "Neo Frontier Kill 1.mp3",
      "Neo Frontier Kill 2.mp3",
      "Neo Frontier Kill 3.mp3",
      "Neo Frontier Kill 4.mp3",
      "Neptune Kill 1.mp3",
      "Neptune Kill 2.mp3",
      "Neptune Kill 3.mp3",
      "Neptune Kill 4.mp3",
      "Oni Kill 1.mp3",
      "Oni Kill 2.mp3",
      "Oni Kill 3.mp3",
      "Oni Kill 4.mp3",
      "Origin Kill 1.mp3",
      "Origin Kill 2.mp3",
      "Origin Kill 3.mp3",
      "Origin Kill 4.mp3",
      "Overdrive Kill 1.mp3",
      "Overdrive Kill 2.mp3",
      "Overdrive Kill 3.mp3",
      "Overdrive Kill 4.mp3",
      "Prelude to Chaos Kill 1.mp3",
      "Prelude to Chaos Kill 2.mp3",
      "Prelude to Chaos Kill 3.mp3",
      "Prelude to Chaos Kill 4.mp3",
      "Prime Kill 1.mp3",
      "Prime Kill 2.mp3",
      "Prime Kill 3.mp3",
      "Prime Kill 4.mp3",
      "Primordium Kill 1.mp3",
      "Primordium Kill 2.mp3",
      "Primordium Kill 3.mp3",
      "Primordium Kill 4.mp3",
      "Protocol 781-A Kill 1.mp3",
      "Protocol 781-A Kill 2.mp3",
      "Protocol 781-A Kill 3.mp3",
      "Protocol 781-A Kill 4.mp3",
      "RGX 11z Pro Kill 1.mp3",
      "RGX 11z Pro Kill 2.mp3",
      "RGX 11z Pro Kill 3.mp3",
      "RGX 11z Pro Kill 4.mp3",
      "Radiant Crisis 001 Kill 1.mp3",
      "Radiant Crisis 001 Kill 2.mp3",
      "Radiant Crisis 001 Kill 3.mp3",
      "Radiant Crisis 001 Kill 4.mp3",
      "Radiant Entertainment System Dance Fever Kill 1.mp3",
      "Radiant Entertainment System Dance Fever Kill 2.mp3",
      "Radiant Entertainment System Dance Fever Kill 3.mp3",
      "Radiant Entertainment System Dance Fever Kill 4.mp3",
      "Radiant Entertainment System K.nock O.ut!! Kill 1.mp3",
      "Radiant Entertainment System K.nock O.ut!! Kill 2.mp3",
      "Radiant Entertainment System K.nock O.ut!! Kill 3.mp3",
      "Radiant Entertainment System K.nock O.ut!! Kill 4.mp3",
      "Radiant Entertainment System Kill 1.mp3",
      "Radiant Entertainment System Kill 2.mp3",
      "Radiant Entertainment System Kill 3.mp3",
      "Radiant Entertainment System Kill 4.mp3",
      "Reaver Kill 1.mp3",
      "Reaver Kill 2.mp3",
      "Reaver Kill 3.mp3",
      "Reaver Kill 4.mp3",
      "Recon Kill 1.mp3",
      "Recon Kill 2.mp3",
      "Recon Kill 3.mp3",
      "Recon Kill 4.mp3",
      "Ruination Kill 1.mp3",
      "Ruination Kill 2.mp3",
      "Ruination Kill 3.mp3",
      "Ruination Kill 4.mp3",
      "Sentinels of Light Kill 1.mp3",
      "Sentinels of Light Kill 2.mp3",
      "Sentinels of Light Kill 3.mp3",
      "Sentinels of Light Kill 4.mp3",
      "Singularity Kill 1.mp3",
      "Singularity Kill 2.mp3",
      "Singularity Kill 3.mp3",
      "Singularity Kill 4.mp3",
      "Sovereign Kill 1.mp3",
      "Sovereign Kill 2.mp3",
      "Sovereign Kill 3.mp3",
      "Sovereign Kill 4.mp3",
      "Spectrum Kill 1.mp3",
      "Spectrum Kill 2.mp3",
      "Spectrum Kill 3.mp3",
      "Spectrum Kill 4.mp3",
      "VCT Team Capsules Kill 1.mp3",
      "VCT Team Capsules Kill 2.mp3",
      "VCT Team Capsules Kill 3.mp3",
      "VCT Team Capsules Kill 4.mp3",
      "Valiant Hero Kill 1.mp3",
      "Valiant Hero Kill 2.mp3",
      "Valiant Hero Kill 3.mp3",
      "Valiant Hero Kill 4.mp3",
      "XERØFANG Kill 1.mp3",
      "XERØFANG Kill 2.mp3",
      "XERØFANG Kill 3.mp3",
      "XERØFANG Kill 4.mp3",
    ];
    source = "Audio/Task/valorant_kill_sounds/${sounds[Random().nextInt(sounds.length)]}";
  }

  Future<void> loadMusic() async {
    _player = AudioPlayer();
    sourceInitialization();
    await _player?.play(AssetSource(source));
  }

  static void dispose() {
    _player?.dispose();
    _player = null;
  }
}